@echo off
echo Creating virtual environment...
python -m venv venv

echo Activating virtual environment...
call venv\Scripts\activate.bat

echo Installing backend dependencies...
cd backend
pip install -r requirements.txt

echo Installing project in development mode...
pip install -e ..

echo Starting FastAPI server...
uvicorn main:app --reload
