@echo off
echo Creating virtual environment...
python -m venv venv_frontend

echo Activating virtual environment...
call venv_frontend\Scripts\activate.bat

echo Installing frontend dependencies...
cd frontend
pip install -r requirements.txt

echo Starting Streamlit server...
streamlit run app.py
